name: Update Nginx configuration

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update-config:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Ensure boofshop.com Nginx config
        run: |
          sudo mkdir -p /etc/nginx/sites-available
          sudo tee /etc/nginx/sites-available/boofshop-com > /dev/null <<'CONFIG'
          server {
              listen 80;
              listen [::]:80;
              server_name boofshop.com www.boofshop.com;

              # Redirect HTTP to HTTPS
              return 301 https://$host$request_uri;
          }

          server {
              listen 443 ssl;
              listen [::]:443 ssl;
              server_name boofshop.com www.boofshop.com;

              ssl_certificate /etc/letsencrypt/live/boofshop.com/fullchain.pem;
              ssl_certificate_key /etc/letsencrypt/live/boofshop.com/privkey.pem;

              ssl_protocols TLSv1.2 TLSv1.3;
              ssl_ciphers 'ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES128-GCM-SHA256';
              ssl_prefer_server_ciphers off;

              location / {
                  proxy_pass http://127.0.0.1:3002;  # Update based on your app
              }
          }
          CONFIG

      - name: Display resulting configuration
        run: sudo cat /etc/nginx/sites-available/boofshop-com
